-- ---------------------------------------------------------------------------
-- PointsCore :: initial schema
--
-- Two ideas drive every table below:
--
--   1. The ledger is append-only. A member's balance is never stored in a
--      column that we UPDATE. It is *derived* from immutable rows. This is how
--      real loyalty and financial systems work: you must be able to answer
--      "why is the balance 4,200?" by replaying history, not by trusting a
--      number somebody could have overwritten.
--
--   2. Points are held in dated *lots*, not as one pooled number. A member who
--      earns 100 points in January and 100 in June holds two lots that expire
--      at different times. Expiry and redemption both consume lots in order.
--      A single pooled balance column cannot express "which points expire when".
-- ---------------------------------------------------------------------------


-- Keeps updated_at honest without the application having to remember.
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ---------------------------------------------------------------------------
-- tiers
-- ---------------------------------------------------------------------------
CREATE TABLE tiers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            TEXT         NOT NULL UNIQUE,
    name            TEXT         NOT NULL,

    -- Qualification threshold: points EARNED in a rolling 12 months. Note this
    -- is deliberately not the current balance -- spending your points must not
    -- demote you, or the programme would punish engagement.
    min_points_12m  INTEGER      NOT NULL,

    -- Tier's own earn bonus, applied on top of promotions (Gold earns 1.25x).
    earn_multiplier NUMERIC(4,2) NOT NULL DEFAULT 1.00,

    sort_order      INTEGER      NOT NULL,

    CONSTRAINT tiers_min_points_non_negative CHECK (min_points_12m >= 0),
    CONSTRAINT tiers_multiplier_positive     CHECK (earn_multiplier > 0),
    CONSTRAINT tiers_sort_order_unique       UNIQUE (sort_order)
);


-- ---------------------------------------------------------------------------
-- members
-- ---------------------------------------------------------------------------
CREATE TABLE members (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT        NOT NULL,
    email       TEXT        NOT NULL,
    tier_id     BIGINT      NOT NULL REFERENCES tiers (id),
    enrolled_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Case-insensitive uniqueness: Asha@x.com and asha@x.com are one person.
-- A plain UNIQUE(email) would happily let both enrol and split their points.
CREATE UNIQUE INDEX members_email_lower_key ON members (lower(email));

CREATE TRIGGER members_set_updated_at
    BEFORE UPDATE ON members
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ---------------------------------------------------------------------------
-- earn_rules
--
-- Rules live in rows, not in Java. Adding "triple points on pastries in
-- December" must be an INSERT, not a redeploy -- that configurability is the
-- whole product in a loyalty platform.
-- ---------------------------------------------------------------------------
CREATE TABLE earn_rules (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        TEXT         NOT NULL UNIQUE,
    name        TEXT         NOT NULL,

    rule_type   TEXT         NOT NULL,

    -- Type-specific parameters. JSONB (not JSON) so Postgres stores it parsed
    -- and can index into it; each rule_type defines its own shape, e.g.
    --   CATEGORY     {"categories": ["COFFEE"]}
    --   DAY_OF_WEEK  {"days": ["SATURDAY", "SUNDAY"]}
    --   MIN_AMOUNT   {"minAmount": 1000}
    conditions  JSONB        NOT NULL DEFAULT '{}'::jsonb,

    multiplier  NUMERIC(4,2) NOT NULL,

    -- Lower runs first. Matters once rules can stop the chain.
    priority    INTEGER      NOT NULL DEFAULT 100,

    active      BOOLEAN      NOT NULL DEFAULT TRUE,

    -- NULL means open-ended in that direction.
    valid_from  TIMESTAMPTZ,
    valid_to    TIMESTAMPTZ,

    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT earn_rules_type_known CHECK (
        rule_type IN ('BASE', 'CATEGORY', 'DAY_OF_WEEK', 'MIN_AMOUNT')
    ),
    CONSTRAINT earn_rules_multiplier_positive CHECK (multiplier > 0),
    CONSTRAINT earn_rules_window_ordered CHECK (
        valid_from IS NULL OR valid_to IS NULL OR valid_to > valid_from
    )
);

CREATE TRIGGER earn_rules_set_updated_at
    BEFORE UPDATE ON earn_rules
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ---------------------------------------------------------------------------
-- transactions -- purchases arriving from the brand's POS
-- ---------------------------------------------------------------------------
CREATE TABLE transactions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id      BIGINT        NOT NULL REFERENCES members (id),

    -- The POS receipt number. Networks retry; a till that sends the same
    -- receipt twice must not mint points twice. The unique constraint below is
    -- what actually enforces that -- checking "does it exist?" in Java first is
    -- a race, because two threads can both read "no" before either writes.
    external_ref   TEXT          NOT NULL,

    amount         NUMERIC(12,2) NOT NULL,
    currency       CHAR(3)       NOT NULL DEFAULT 'INR',
    category       TEXT          NOT NULL,
    occurred_at    TIMESTAMPTZ   NOT NULL,

    -- Cached result of the rules engine, for display and debugging. The lots
    -- and ledger remain the source of truth.
    points_awarded INTEGER       NOT NULL DEFAULT 0,

    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT transactions_amount_positive CHECK (amount > 0),
    CONSTRAINT transactions_points_non_negative CHECK (points_awarded >= 0),

    -- Scoped per member: two different coffee shops may both issue receipt
    -- "A-1001", and they are genuinely different purchases.
    CONSTRAINT transactions_member_ref_unique UNIQUE (member_id, external_ref)
);

CREATE INDEX transactions_member_occurred_idx
    ON transactions (member_id, occurred_at DESC);


-- ---------------------------------------------------------------------------
-- point_lots -- dated buckets of points, consumed oldest-expiring first
-- ---------------------------------------------------------------------------
CREATE TABLE point_lots (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id        BIGINT      NOT NULL REFERENCES members (id),

    -- NULL for lots created by a manual adjustment rather than a purchase.
    transaction_id   BIGINT      REFERENCES transactions (id),

    points_earned    INTEGER     NOT NULL,

    -- The one mutable number in the system. Redemption and expiry both draw it
    -- down. Every change must be accompanied by a ledger row in the SAME
    -- database transaction -- that pairing is the invariant the whole design
    -- rests on, and there is a test that checks it holds.
    points_remaining INTEGER     NOT NULL,

    earned_at        TIMESTAMPTZ NOT NULL,
    expires_at       TIMESTAMPTZ NOT NULL,

    CONSTRAINT point_lots_earned_positive     CHECK (points_earned > 0),
    CONSTRAINT point_lots_remaining_in_range  CHECK (points_remaining >= 0
                                                 AND points_remaining <= points_earned),
    CONSTRAINT point_lots_expiry_after_earned CHECK (expires_at > earned_at)
);

-- The consumption query is always "live lots for this member, soonest expiry
-- first". A partial index skips fully-drained lots entirely, so the index stays
-- small even after years of history.
CREATE INDEX point_lots_live_fifo_idx
    ON point_lots (member_id, expires_at, id)
    WHERE points_remaining > 0;


-- ---------------------------------------------------------------------------
-- ledger_entries -- append-only history; the source of truth for balances
-- ---------------------------------------------------------------------------
CREATE TABLE ledger_entries (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id   BIGINT      NOT NULL REFERENCES members (id),

    entry_type  TEXT        NOT NULL,

    -- Signed: EARN is positive, REDEEM and EXPIRE are negative, ADJUST is
    -- either. Balance is therefore SUM(points) -- one query, no special cases.
    points      INTEGER     NOT NULL,

    lot_id      BIGINT      REFERENCES point_lots (id),

    -- Loose polymorphic pointer to whatever caused this entry (a transaction, a
    -- redemption, an expiry run). Deliberately not a foreign key: it targets
    -- different tables per row.
    ref_type    TEXT,
    ref_id      BIGINT,

    description TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ledger_entries_type_known CHECK (
        entry_type IN ('EARN', 'REDEEM', 'EXPIRE', 'ADJUST')
    ),
    CONSTRAINT ledger_entries_points_non_zero CHECK (points <> 0),

    -- Sign must match the entry type, so a bug cannot file a "redemption" that
    -- quietly increases someone's balance.
    CONSTRAINT ledger_entries_sign_matches_type CHECK (
        (entry_type = 'EARN'                    AND points > 0) OR
        (entry_type IN ('REDEEM', 'EXPIRE')     AND points < 0) OR
        (entry_type = 'ADJUST')
    )
);

CREATE INDEX ledger_entries_member_created_idx
    ON ledger_entries (member_id, created_at DESC, id DESC);

-- Append-only, enforced by the database rather than by good intentions. Even a
-- buggy service, a stray JPA dirty-check, or someone at a psql prompt cannot
-- rewrite history.
CREATE OR REPLACE FUNCTION ledger_entries_reject_mutation() RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION
        'ledger_entries is append-only; attempted % on entry id %',
        TG_OP, OLD.id;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER ledger_entries_immutable
    BEFORE UPDATE OR DELETE ON ledger_entries
    FOR EACH ROW EXECUTE FUNCTION ledger_entries_reject_mutation();


-- ---------------------------------------------------------------------------
-- rewards
-- ---------------------------------------------------------------------------
CREATE TABLE rewards (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        TEXT        NOT NULL UNIQUE,
    name        TEXT        NOT NULL,
    description TEXT,
    cost_points INTEGER     NOT NULL,
    stock       INTEGER     NOT NULL,
    active      BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT rewards_cost_positive     CHECK (cost_points > 0),
    -- Stock can never go below zero. Two members racing for the last mug will
    -- find that one of their transactions fails here rather than overselling.
    CONSTRAINT rewards_stock_non_negative CHECK (stock >= 0)
);

CREATE TRIGGER rewards_set_updated_at
    BEFORE UPDATE ON rewards
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ---------------------------------------------------------------------------
-- redemptions
-- ---------------------------------------------------------------------------
CREATE TABLE redemptions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id       BIGINT      NOT NULL REFERENCES members (id),
    reward_id       BIGINT      NOT NULL REFERENCES rewards (id),

    -- Supplied by the caller in an Idempotency-Key header. A phone that loses
    -- signal mid-request will retry; the retry must return the original
    -- redemption, not spend the points again. Globally unique, because the key
    -- is a client-generated UUID.
    idempotency_key TEXT        NOT NULL UNIQUE,

    points_spent    INTEGER     NOT NULL,
    status          TEXT        NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at    TIMESTAMPTZ,

    CONSTRAINT redemptions_points_positive CHECK (points_spent > 0),
    CONSTRAINT redemptions_status_known CHECK (
        status IN ('COMPLETED', 'CANCELLED', 'FAILED')
    )
);

CREATE INDEX redemptions_member_created_idx
    ON redemptions (member_id, created_at DESC);
