-- ---------------------------------------------------------------------------
-- tier_changes -- an audit trail for movement between tiers
--
-- Same reasoning as the points ledger: a member's tier is visible on
-- members.tier_id, but "why am I no longer Gold?" is not answerable from a
-- single column. Every recalculation that changes a tier records what it saw
-- and what it decided, so a support agent can explain a demotion instead of
-- guessing.
-- ---------------------------------------------------------------------------

CREATE TABLE tier_changes (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id         BIGINT      NOT NULL REFERENCES members (id),

    -- NULL on enrolment, when there was no previous tier.
    from_tier_id      BIGINT      REFERENCES tiers (id),
    to_tier_id        BIGINT      NOT NULL REFERENCES tiers (id),

    -- The rolling-12-month figure the decision was based on. Stored rather
    -- than recomputed, because the window moves: re-running the sum a month
    -- later gives a different answer and would not explain this decision.
    qualifying_points INTEGER     NOT NULL,

    reason            TEXT        NOT NULL,
    changed_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT tier_changes_reason_known CHECK (
        reason IN ('INITIAL', 'UPGRADE', 'DOWNGRADE')
    ),
    CONSTRAINT tier_changes_points_non_negative CHECK (qualifying_points >= 0),
    CONSTRAINT tier_changes_actually_changed CHECK (
        from_tier_id IS NULL OR from_tier_id <> to_tier_id
    )
);

CREATE INDEX tier_changes_member_changed_idx
    ON tier_changes (member_id, changed_at DESC);
