-- ---------------------------------------------------------------------------
-- user_accounts -- who may call the API, and as whom
--
-- Kept apart from members on purpose. A member is a loyalty customer with
-- points and a tier; an account is a login. Staff need the second without the
-- first, and one day a member may want to log in through a provider that
-- gives us no password at all. Conflating the two would put password hashes
-- on a table that half the application reads for other reasons.
-- ---------------------------------------------------------------------------

CREATE TABLE user_accounts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         TEXT        NOT NULL,
    password_hash TEXT        NOT NULL,
    role          TEXT        NOT NULL,

    -- The member this login acts for. NULL for staff.
    member_id     BIGINT      REFERENCES members (id),

    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT user_accounts_role_known CHECK (role IN ('ADMIN', 'MEMBER')),

    -- A MEMBER account must point at a member, and an ADMIN must not. The
    -- authorisation code assumes this, so the database enforces it.
    CONSTRAINT user_accounts_member_matches_role CHECK (
        (role = 'MEMBER') = (member_id IS NOT NULL)
    )
);

-- Same case-insensitive rule as members.email: one login per person.
CREATE UNIQUE INDEX user_accounts_email_lower_key ON user_accounts (lower(email));

-- One login per member.
CREATE UNIQUE INDEX user_accounts_member_key ON user_accounts (member_id)
    WHERE member_id IS NOT NULL;

CREATE TRIGGER user_accounts_set_updated_at
    BEFORE UPDATE ON user_accounts
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
